### ISSUE TITLE
Link-Verification

### ISSUE THREAD

**Issue by Gapemaster6** [Kourva/TempMailBot#1]
i just hosted this and I like it but seems so limited, can you make it work for link verification too?

**Comment by Kourva** [comment]
#### Hi @Gapemaster6,

I'm glad you liked it. I looked at the example response I received from [mail.tm](http://mail.tm/) and found a way to display the entire attachment from the verification emails, such as link verification. I will update the source code soon.

For further clarification, the complete message is stored in the `downloadUrl` key within the response data, which is in JSON format. The attachment found at the following URL is encoded in base64, so we need to decode it in order to obtain the attachment in HTML format. Once we have the HTML syntax, we can format it and convert it into markup to display it to the user. 

Thanks for your report!

**Comment by Kourva** [comment]
The source code has been updated, and link verification is now supported.

**Comment by Gapemaster6** [comment]
Wonderful news, I'll try this! Thanks for the prompt response!

**Comment by Kourva** [comment]
> Wonderful news, I'll try this! Thanks for the prompt response!

You're welcome. Glad you liked it.
